export enum PersonalRole {
  DOCTOR = 'DOCTOR',
  ASSISTANT = 'ASSISTANT',
  ANESTHESIOLOGIST = 'ANESTHESIOLOGIST',
  SCRUB_NURSE = 'SCRUB_NURSE',
  CIRCULATING_NURSE = 'CIRCULATING_NURSE',
  ADMIN = 'ADMIN',
  TECHNICIAN = 'TECHNICIAN',
}