export const CIRUGIAS_SERVICE = 'CIRUGIAS_SERVICE';
export const PACIENTES_SERVICE = 'PACIENTES_SERVICE';
export const PERSONAL_SERVICE = 'PERSONAL_SERVICE';
export const SERVICIOS_SERVICE = 'SERVICIOS_SERVICE';
export const QUIROFANOS_SERVICE = 'QUIROFANOS_SERVICE';