export const SURGERY_SERVICE = 'SURGERY_SERVICE';
export const PATIENT_SERVICE = 'PATIENT_SERVICE';
export const PERSONAL_SERVICE = 'PERSONAL_SERVICE';
export const SERVICE_SERVICE = 'SERVICE_SERVICE';
export const OPERATING_ROOM_SERVICE = 'OPERATING_ROOM_SERVICE';
export const SCHEDULE_SERVICE = 'SCHEDULE_SERVICE';